### ISSUE TITLE
Demo Android app not working

### ISSUE THREAD

**Issue by petruscurtu** [googlecodelabs/fido2-codelab#9]
Hello

The demo app for Android is no longer working. 
I followed the tutorial at https://codelabs.developers.google.com/codelabs/fido2-for-android.
I tried to follow the tutorial, to make my own glitch and also using the finished implementation.
Nothing works.

`2020-11-13 18:46:51.465 5313-6730/com.example.android.fido2 E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.example.android.fido2, PID: 5313
    com.example.android.fido2.api.ApiException: Cookie not found: username
        at com.example.android.fido2.api.AuthApi.findSetCookieInResponse(AuthApi.kt:565)
        at com.example.android.fido2.api.AuthApi.username(AuthApi.kt:82)
        at com.example.android.fido2.repository.AuthRepository$username$1.run(AuthRepository.kt:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by agektmr** [comment]
@yaraki This is probably because I changed the server side recently. Can you have a look?
